name: Insider UI Test Cases

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Maven Install Without Tests
        run: mvn install -DskipTests
      - name: Maven Test With Browser Parameters
        run: mvn surefire-report:report -DBROWSER="CHROME"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Download Test Report
          path: |
            target/site
            log
            screenshots
